server {
    listen 80;
    listen 8010;
    server_name cmd.flexgrafik.nl _;

    # Wylaczenie autoryzacji dla Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
        auth_basic off;
    }

    # Proxy do NodeJS / PM2 VCMS
    location / {
        # Ochrona Frontu za pomoca Basic Auth
        auth_basic "VCMS Restricted Area: Identification Required";
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        proxy_pass http://127.0.0.1:8001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        
        # Transparentne logowanie IP w Node (dla monitoringu)
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
